### ISSUE TITLE
[Feature] Create language files as part of "create a new project"

### ISSUE THREAD

**Issue by SirLich** [solvedDev/bridge.#104]
**Summary**
Currently, "Create a new project" is placing pack name and pack description directly into the manifest file. 

**Alternatives/Considerations**
I believe that pack name and description should be automatically placed into the en.lang file, and that a default language file should be created. 

Using the lang file structure is very much recommended, cause it allows easy translations and such. I believe that this should be the default behavior for creating a new project.

**Comment by SirLich** [comment]
Related: You currently cannot create language files using bridge, so you need to create them in a third party text editor, or copy/paste using the file explorer.

**Comment by solvedDev** [comment]
Both things should definitely be changed 👍
