### ISSUE TITLE
[Feature] Duplication of behavior grouping (like copy/paste)

### ISSUE THREAD

**Issue by SirLich** [solvedDev/bridge.#105]
**Summary**
Duplication functionality when clicking on a behavior group. This could be implemented as a button that sits by "copy/paste/delete/move-up/move-down". This would either rename the parent behavior to something like behavior0 (atom functionality), or maybe open a dialogue where you can type the new name. 

This would be useful in scenarios like events, where its very hard to duplicate an event. Currently, you need to: copy the event, rename the event, paste the event. The rename is needed cause if you paste the "same name", it will do really weird stuff, and place the behavior grouping further down in the tree (bug report incoming..?)

**Alternatives/Considerations**
Alternatively, this functionality could be implemented as a bugfix for pasting the "same name" into a group. Use the renaming of behavior0 as explained above.

**Comment by solvedDev** [comment]
I've implemented the following solution: If a copied JSON node ends with "_<NUMBER>", bridge. will auto increment the number

**Comment by SirLich** [comment]
Hey @solvedDev, I think that it would be worth it to revisit this. 

I would recommend that if you paste a section into a section that contains a duplicate key (essentially duplicating), it would be listed as "name"-copy, or something. 

There are tonnes of places where you want to copy/paste a component group, or an event. These aren't going to naturally be named like "component_group_1" (which your solution would work on). They are going to be named things like "skin_color_blue" and "skin_color_red".

I really stand by the fact that copy/pasting "skin_color_red" and having it show up as "skin_color_red-copy" would be super useful.

The current implementation (even with your solution) means that you have to work pretty hard to duplicate a section.

**Comment by solvedDev** [comment]
👍 Reopened

**Comment by solvedDev** [comment]
bridge. will append "_copy" to the object keys instead of merging the pasted JSON with the existing code starting with the next major version. The old changes still apply
