### ISSUE TITLE
Bridge is stuck loading

### ISSUE THREAD

**Issue by MBroOfficial** [solvedDev/bridge.#11]
When I launch bridge it just says Loading... and doesn't progress any further, settings is empty due to this too and I've changed permissions on the folder it saves behaviour packs to but it hasn't loaded up fully still. Please help. Thanks, MBroOfficial. (I am running Bridge 0.12.2)

UPDATE: I tried launching bridge as administrator and that made no difference either.
UPDATE 2: I downloaded Bridge 0.13.0-pre9 and it worked.

**Comment by MBroOfficial** [comment]
> When I launch bridge it just says Loading... and doesn't progress any further, settings is empty due to this too and I've changed permissions on the folder it saves behaviour packs to but it hasn't loaded up fully still. Please help. Thanks, MBroOfficial.

**Comment by solvedDev** [comment]
👍 v0.13.0 has some changes to fix exactly this problem. Basically the way I was accessing Minecraft's app data wasn't working on all windows machines
