### ISSUE TITLE
[BUG] Creating files without a project

### ISSUE THREAD

**Issue by ShadowsWithin** [solvedDev/bridge.#112]
It is NOT loading! I saw a report on this but it said it was fixed. But it is still not working!!!

See if yours is doing the same:
Steps:
1. Go to 'FILE'
2. Click on 'NEW FILE'
3. Scroll down to anything (block, entity, etc...)
4. Observe result

When I did this It never loads!
It is NOT supposed to take 3 hours to load (and it still didn't)

1)
![image](https://user-images.githubusercontent.com/58058412/69394374-b33a7c80-0c90-11ea-994c-2acd8a11ab1e.png)
2)
![image](https://user-images.githubusercontent.com/58058412/69394406-ccdbc400-0c90-11ea-9e7f-3545f58019c6.png)
3)
![image](https://user-images.githubusercontent.com/58058412/69394422-d7965900-0c90-11ea-8410-55218ad166f3.png)
(its been on this screen for hours ^)

This is on this(these) device(s) (as for what I know so far)
 - Windows 10

**Comment by solvedDev** [comment]
@ShadowsWithin You currently have to create a project first (look at the sidebar). I'll keep this issue open though to address that files can currently be created without a project

**Comment by solvedDev** [comment]
It won't be possible to create files without a project anymore with the next version of bridge.

**Comment by ShadowsWithin** [comment]
Ok, thanks :)

**Comment by ShadowsWithin** [comment]
Its working now, I'm sorry about this. Thanks for telling me this 👍
