### ISSUE TITLE
[BUG] Import add-on on mobile

### ISSUE THREAD

**Issue by Redstone-Hamster** [solvedDev/bridge.#115]
None of the add-ons currently load on mobile for me

**Comment by solvedDev** [comment]
Could you please provide some more information? Which device are you using? On which version of Minecraft are you playing and which error do you get?

**Comment by Redstone-Hamster** [comment]
Version: 1.13.0.1
Platform: Android
Error: "Some of your behavior or resource packs didn't load" (Something
along those lines)

**Comment by solvedDev** [comment]
Try the following: Set the manifest's format version of your project to "2" and then repackage your project. Please also check that your're running the latest bridge. version
