### ISSUE TITLE
[BUG] Mac .DS_Store bug

### ISSUE THREAD

**Issue by destruc7i0n** [solvedDev/bridge.#118]
**Summary**
When scanning my development behaviour packs folder, bridge takes my .DS_Store files and interprets them as behaviour packs, and then freezes in the loading phase at all.

**To Reproduce**
Use a Mac and load up the app, with having a .DS_Store file in the folder.

**Observed behavior**
<img width="1792" alt="Screen Shot 2019-11-30 at 2 36 28 PM" src="https://user-images.githubusercontent.com/6181960/69905261-02626a80-137f-11ea-8ce3-8f1be37b06d7.png">

**Expected behavior**
.DS_Store files to be ignored. Maybe add a check to ensure that each file is a directory before making the bridge metadata and such?

**Screenshots / File Attachments**
See above.

**Platform (please complete the following information):**
 - OS: macOS 10.14.6
 - App Version: 0.13.26

**Additional context**
N/A

**Comment by solvedDev** [comment]
Thanks for the report :)
