### ISSUE TITLE
Toggle for Hardware Acceleration

### ISSUE THREAD

**Issue by jaxspades** [solvedDev/bridge.#123]
This app is amazing! I love that Minecraft add-ons make sense now, so thank you!

I would love to be able to twitch stream and work on add-ons, but OBS shows the bridge. editor window as a black screen. This seems to happen with Electron apps that have hardware acceleration.

Is there a way where I can turn off hardware acceleration?

**Comment by solvedDev** [comment]
![image](https://user-images.githubusercontent.com/33347616/70548553-0bb7b800-1b73-11ea-9f08-371c83cf2fbd.png)

Added a new setting for the next update 👍

**Comment by solvedDev** [comment]
Added with commit 8f6b978b8ed89ed68ed6616865e263c3a17d7138
