### ISSUE TITLE
[Feature] Support for 32 bit OS?

### ISSUE THREAD

**Issue by kouichi12** [solvedDev/bridge.#125]
Hello, I like to request for a build for 32-bit system, as I only have a single old computer to do stuff around here.

I did tried to build my own from the source but unsuccessful with NPM install to build it.
I mostly play on android and I would love to have this app on my computer to builds addons more effectively than using text editor.

I know this feature is so meaningless forothers but I guess it's worth the shot.

Thank you.

**Comment by solvedDev** [comment]
Heyo, going to take a look at supporting 32bit Windows :)

**Comment by solvedDev** [comment]
The next versions should work on 32bit Windows :D
Please let me know whether everything's working fine once it's available

**Comment by kouichi12** [comment]
Ah Thank you! :)

I'll let you know for any bugs!
