### ISSUE TITLE
RP

### ISSUE THREAD

**Issue by coolkidsrule101** [solvedDev/bridge.#22]
when i clicked on create on the resource pack button nothing happens after i create it. i checked my folder and there nothing in resource development.

ps come back to discord pls from artistic-waffle

**Comment by solvedDev** [comment]
Please provide the pre-release you're using, @coolkidsrule101. I am unable to reproduce the issue

**Comment by coolkidsrule101** [comment]
0.13.0

**Comment by solvedDev** [comment]
Well, "0.13.0" is not the exact pre-release. Please download the latest pre-release and try it again :)

If you still have no luck, open the settings menu and select the last tab in it. Enable the error pop-ups and try to create a RP again. If a red window appears, please make a screenshot of it and send it in here

**Comment by coolkidsrule101** [comment]
same problem with 0.13.0 pre 11

**Comment by solvedDev** [comment]
Have you tried the other thing I've described?

**Comment by coolkidsrule101** [comment]
![image](https://user-images.githubusercontent.com/31514218/61555245-ee9c1480-aa2c-11e9-94c0-4eeef13d4536.png)

**Comment by solvedDev** [comment]
Do you have Minecraft Win10 installed on your computer, @coolkidsrule101?

**Comment by coolkidsrule101** [comment]
no only on linux

**Comment by solvedDev** [comment]
bridge. currently requires a version of Minecraft being installed on your computer. There are ongoing efforts to remove this need by adding the option to set a new default directory to load/store behavior and resource packs in.
