### ISSUE TITLE
bridge. gets addons confused.

### ISSUE THREAD

**Issue by RandomYT2802** [solvedDev/bridge.#26]
Sometimes bridge. thinks I'm looking in one addon, when I'm looking in a completely different one. It shows the name of the addon I'm looking in, the icon, but not the files. At the moment, I'm just editing raw .json because I know how, but I did rely on bridge, to make it easier. If you can, please fix. Also, I tried reinstalling it, and that didn't work.

**Comment by solvedDev** [comment]
@RandomYT2802 Are you on v0.13.2?

**Comment by jaydenhumphrey** [comment]
Same here. I will click to switch pack but it keeps it's focus on the one it started on

**Comment by solvedDev** [comment]
Latest version? (v0.13.2) @jaydenhumphrey

**Comment by jaydenhumphrey** [comment]
v0.13.2 @solvedDev

**Comment by solvedDev** [comment]
Thanks! This should have been fixed by commit eb7c13421ee0f10b1f8cee5e21dd9b58a55e51f6; will be part of the next update :)

**Comment by RandomYT2802** [comment]
yep

**Comment by solvedDev** [comment]
Thanks for the report & answers! :)
