### ISSUE TITLE
[BUG] Bridge gets a syntax error when opening the program.

### ISSUE THREAD

**Issue by bschurman1** [solvedDev/bridge.#31]
Bridge gets an error which reads "Syntax Error: Unexpected token / in JSON at position 0"

Most likely caused by comments in the manifests (I found 2 pack manifests starting with something like "//bridge file version X"

**Comment by solvedDev** [comment]
Fixed with 673e7d751c9acd47ac1be21d16138a661dc696b3; scheduled for v0.13.4 - Thanks for your report!
