### ISSUE TITLE
[Feature] Mob Behavior Templates

### ISSUE THREAD

**Issue by Gekocaretaker1** [solvedDev/bridge.#34]
I was watching one of the Bridge tutorials by DanRobzProbz and I saw that he had access to the player and other mobs behaviors and I was wondering how do I access those?

**Comment by solvedDev** [comment]
You can currently grab the default pack from aka.ms/MinecraftBetaBehaviors. I want to ship deeper integration of some vanilla files into bridge. in one of the next releases
