### ISSUE TITLE
[BUG] Saving broken

### ISSUE THREAD

**Issue by DanRobzProbz** [solvedDev/bridge.#35]
When I create a behaviour pack(new project) save the entity it just continues to load therefore not saving my work.

1. Go to 'New Project' & start to create your entity
2. Create your entity.
3. Save it, as you would using either ctrl+s/save option.
4. The save bar just stays up...
(this has happend 3xtimes now)

I just wanted to save my progress.
See below;-
![Screenshot 2019-08-20 11 19 49(3)](https://user-images.githubusercontent.com/20096690/63339313-8480d300-c33c-11e9-8b9a-458e330f7cb0.png)

![Screenshot 2019-08-20 11 19 39(2)](https://user-images.githubusercontent.com/20096690/63339331-91052b80-c33c-11e9-94d6-e1a8de5740e6.png)

 - OS: [Windows 10]
 - App Version [See screenshot]
![Screenshot 2019-08-20 11 22 21](https://user-images.githubusercontent.com/20096690/63339464-da557b00-c33c-11e9-9310-e658e9a1f997.png)

This has only started to happen since I updated the program this morning...

Thanks 
Dan,

**Comment by solvedDev** [comment]
@DanRobzProbz Thanks a lot for your report! After investigations, I came to the conclusion that the bug is already fixed in the latest pre-release published two days ago:

https://github.com/solvedDev/bridge./releases/tag/v0.13.4-pre
