### ISSUE TITLE
[BUG] Resource packs stuck loading

### ISSUE THREAD

**Issue by RandomYT2802** [solvedDev/bridge.#40]
Resource packs are stuck loading in v1.13.5.
After clicking on "Resource Packs" icon, it procedes with a loading bar near the files, and doesn't do anything else.

It could just be me, but I wanted to make sure you knew just in case.
This is a pain in the back though, because now I can't edit my resource .json files.

**Comment by solvedDev** [comment]
@RandomYT2802, please follow the following steps so I can track your issue down:
1) Open the settings window (FILE > PREFERENCES > SETTINGS)
2) Switch to the last tab inside the settings window
3) Open the developer console
4) Send me a screenshot of what is inside the console

As soon as I have this screenshot, I can investigate the logs, track the issue down and schedule a hotfix.

**Comment by RandomYT2802** [comment]
![image](https://user-images.githubusercontent.com/50797719/63616152-d9dc0f00-c5de-11e9-8d19-22cfc32a91bd.png) here you go. I still have 1.13.3, so i've been using that.

**Comment by solvedDev** [comment]
It looks like one of the RPs you have in the "development_resource_packs" folder does not contain a valid manifest. If you find this folder manually & add a manifest, the program should run correctly again.

I am also working on fixing this for the next version; a folder without a manifest won't stop loading other RPs anymore.

**Comment by solvedDev** [comment]
Leaving this open until it's actually fixed in bridge.'s code; thanks a lot for the report! :)
