### ISSUE TITLE
[BUG] Missing Dependencies

### ISSUE THREAD

**Issue by Gekocaretaker1** [solvedDev/bridge.#41]
When I look at the addon in Minecraft it shows this
![image](https://user-images.githubusercontent.com/51133807/63631029-01cb7280-c5df-11e9-80a8-2395083a0361.png)

**Comment by solvedDev** [comment]
Thanks for the report! This is normally a problem with Minecraft's validator. If you apply the BP to a world and the RP gets then applied automatically, everything is working fine.
