### ISSUE TITLE
[Feature] Single instance RP file support

### ISSUE THREAD

**Issue by RandomYT2802** [solvedDev/bridge.#48]
This is purely just a request:

A resource pack's blocks.json file can do so many things, that I thinks it's worth making it compatible with bridge.. There is only a few issues with doing this:
- Some aspects haven't been documented.
- Despite it's functionality, it may still be too minor, and a waste of time.

now that i think about it, it's not documented enough to actually add, but you're solvedDev. I'm sure you'll figure it out.

**Comment by solvedDev** [comment]
There are ongoing efforts to support the item_texture.json, blocks.json, sounds.json, terrain_texture.json, ... files in the very near future.
**Estimated integration:** One of the next few updates

**Comment by solvedDev** [comment]
Happy to have this in with 32d4b41517b39affcac0ab6e7b60538f4bd78444! Will be part of the next update :)
