### ISSUE TITLE
Resource Packs Are Still Done By Hand

### ISSUE THREAD

**Issue by truegamerxy** [solvedDev/bridge.#52]
I would love to be able to have a simple way to connect are blocks and there textures. The best way would be drag and drop but even I know thats unrealistic maybe a simple tag system? Sorry I dont know how to tag I dont use GitHub that much.

**Comment by RandomYT2802** [comment]
solved is already working on this.

**Comment by solvedDev** [comment]
Connecting textures to items and blocks easier will be part of the next update! :)
