### ISSUE TITLE
[Feature] Identifier optimisation

### ISSUE THREAD

**Issue by RandomYT2802** [solvedDev/bridge.#53]
Can you add an option when you start a pack to choose an identifier that will be automatically placed at the start of an item. For example:

Identifier:
bridge

Item name: solveddev > bridge:solveddev.

You don't have to choose the option, but it's there if you need it.
I just find it tedious to type the identifier every time i make an item/block/entity.

**Comment by solvedDev** [comment]
I think I have this upcoming already with a default identifier being combined from the namespace "bridge" and the current file name. I'll check the different code branches and report back when you can expect this feature! :)

Example: After creating the file "ruby_sword.json", bridge. would propose the identifier "bridge:ruby_sword"

**Comment by solvedDev** [comment]
Okay, that's in fact already on the master branch. Should be part of the next update 👍
