### ISSUE TITLE
[BUG] Resource pack files generate inside behaviour pack upon project creation

### ISSUE THREAD

**Issue by Hyperfied** [solvedDev/bridge.#56]
**Summary**
Whenever I create a project, the resource pack files (blocks.json, sounds folder etc) generate inside the behaviour pack. The resource pack files generate correctly into the resource pack.

**To Reproduce**
Create a project and they should generate

**Observed behavior**
Resource pack files also generated inside the behaviour pack
**Expected behavior**
Only the manifest.json file generates inside the behaviour pack

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - App Version: [e.g. 0.13.6]

**Comment by solvedDev** [comment]
Thanks for the report! I've reproduced the bug & am now working on a fix
