### ISSUE TITLE
[BUG] bridge. can't access to the config files on macOs

### ISSUE THREAD

**Issue by MisteFr** [solvedDev/bridge.#70]
**Summary**
You can't change any settings on macOs version of bridge. because of bridge. getting config folder&files creation&reading-access refused.
**To Reproduce**
1. Run bridge. for macOs
2. Try changing the custom data directory
3. Check the console

**Observed behavior**
The data directory wasn't changed and an error was thrown in the console.
**Expected behavior**
The data directory changed and no error.

**Screenshots / File Attachments**
```
Error: EACCES: permission denied, open '/Users/USER/.bridge/data/settings'
    at Object.openSync (fs.js:447)
    at Object.func (electron/js2c/asar.js:155)
    at Object.func [as openSync] (electron/js2c/asar.js:155)
    at Object.writeFileSync (fs.js:1206)
```

**Platform (please complete the following information):**
 - OS: macOs
 - App Version: 0.13.7

**Comment by solvedDev** [comment]
Probably fixed with a30e5faf2c1d75ab54fec3010f71c1e78f0c4336 and 65bcb9bc5068073a9f1dd867aa9e3faf2eb87d42
