### ISSUE TITLE
[BUG] bridge. doesn't close properly on macOs

### ISSUE THREAD

**Issue by MisteFr** [solvedDev/bridge.#71]
**Summary**
When you close bridge. window on macOs, bridge. process isn't stopped (the app is still running) and if you re try opening it after nothing happen.

**To Reproduce**
1. Open bridge. on macOs
2. Close bridge. window
3. Try reopening bridge.
4. Observe result

**Observed behavior**
Bridge. isn't getting closed properly and can't be reopened if you don't force close the application once the window was closed.
**Expected behavior**
Bridge. closing properly.

**Platform (please complete the following information):**
 - OS: macOs
 - App 0.13.7

**Comment by YOYITsM3M8** [comment]
where is macos download??

**Comment by solvedDev** [comment]
**Wrong issue;** #72
You have to compile a build yourself. I currently don‘t provide them upon drafting a new release because I still do that process completely by hand.
