### ISSUE TITLE
[BUG] Creating RPs

### ISSUE THREAD

**Issue by ChadCross** [solvedDev/bridge.#75]
**Summary**
Making a resource pack and unable to manifest it n the folder or sidebar in bridge

**To Reproduce**
1. Go to Resource Pack
2. Click on Create
3. Enter the information needed
4. Click Create
5. Nothing happen

**Observed behavior**
Nothing happened not a single tab to explore or use to create resource pack. (I've watched danrobzprobz tutorial to add .res at the title of the resource).

**Expected behavior**
To get what I have watched from the tutorial video as I want to try it out and have some add-ons I want to try or get.

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.
![image](https://user-images.githubusercontent.com/55026588/65497221-70586480-deec-11e9-82cd-8b6e36241968.png)
![image](https://user-images.githubusercontent.com/55026588/65497277-8a924280-deec-11e9-8687-34f630d9225f.png)

**Platform:**
 -  Windows 10 Pro
 - App Version:  0.13.7

**Comment by ChadCross** [comment]
current step:

Doing the resource tab
![image](https://user-images.githubusercontent.com/55026588/65585240-bd077280-dfb4-11e9-9f88-ea8aabb38645.png)

Clicking Create
![image](https://user-images.githubusercontent.com/55026588/65585306-d7d9e700-dfb4-11e9-9357-54fa20edbbd2.png)

nothin happened. maybe it was just me or something happened wrongly. I did dl all the files on the main exe and zip file.

**Comment by ChadCross** [comment]
![image](https://user-images.githubusercontent.com/55026588/65586485-d4dff600-dfb6-11e9-9a93-6cc6f0658f17.png)
the files and location on my pc

**Comment by solvedDev** [comment]
@ChadCross, thanks! There's definitely something going wrong here (error symbol at the top of the console). Could you please switch to the "console" tab inside the developer console and make another screenshot?

**Comment by ChadCross** [comment]
![image](https://user-images.githubusercontent.com/55026588/65587680-d3afc880-dfb8-11e9-90ed-accf9f46c74e.png)
really wrong but i'm not into coding really.

**Comment by solvedDev** [comment]
Okay, this issue actually happens because you don't have Minecraft installed on your computer. This isn't fully supported yet although I am working on it. Keeping this issue open until better support has arrived

**Comment by ChadCross** [comment]
but can i make resource pack for the behaviour pack that i am making? i read enough about the beta add on guide on bridge and minecraft wiki. i mean it would only be separated or mcaddon package.

**Comment by solvedDev** [comment]
Yes, bridge. generally does support RPs but it also only works 100% smoothly with Minecraft installed. I haven't really tried it without yet.
