### ISSUE TITLE
New File drop down option[Feature]

### ISSUE THREAD

**Issue by JumperXxXCables** [solvedDev/bridge.#77]
When clicking on new file from the file menu whether in bp or rp it automatically by default creates a bp file. I know that you can click the icon for new file in each but I would like to have the option no mater which one I am clicked in to create either one.

**Comment by solvedDev** [comment]
@JumperXxXCables, actually clicking on the "New File" option inside the FILE menu opens a dialog with RP and BP files. Currently, RP files are at the very bottom but soon all files will be sorted alphabetically

**Comment by JumperXxXCables** [comment]
Ok I wasn't aware of that thx
