### ISSUE TITLE
[BUG] Tools then escape

### ISSUE THREAD

**Issue by BlkCatGmg** [solvedDev/bridge.#82]
**Summary**
It's a simple bug. When you're in the tools menu and press the ESC button you'll get an error.

**To Reproduce**
1. Open the tools menu
2. Press escape and if you have dev_mode enabled you'll get an error

**Observed behavior**
Nothing really happens it's a low priority bug
**Expected behavior**
Expected it not to happen. I guess.

**Platform (please complete the following information):**
Windows 10
0.13.8

**Comment by solvedDev** [comment]
Reproduced & fixed for the next update! Thanks for the report! :D
