### ISSUE TITLE
[BUG] bridge. Compiling works, but causes program halt.

### ISSUE THREAD

**Issue by CarterPatterson** [solvedDev/bridge.#83]
**Summary**
When compiling, bridge. successfully compiles and saves the files, but then will get stuck at the "loading" screen causing user to have to force close the program.

**To Reproduce**
1. Open a file in bridge.
2. Compile. "ctrl+k"
**Observed behavior**
See summary.
**Expected behavior**
bridge. should save and compile the file, the loading screen should open and then close.

**Screenshots / File Attachments**
![bridge_error](https://user-images.githubusercontent.com/42452101/65924451-9b85fc80-e3a1-11e9-9c82-d6729537df8d.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - bridge. Version: 0.13.10

**Comment by solvedDev** [comment]
Thanks for the report!
This specific issue requires a plugin update; it's not an issue with the program itself.
