### ISSUE TITLE
[Feature] Syntax highlighting for .lang files

### ISSUE THREAD

**Issue by GitWither** [solvedDev/bridge.#87]
**Summary**
A syntax highlighting for .lang files which will make it easier to edit them. Attached is a screenshot of how a Visual Studio Code extension executes this.
![image](https://user-images.githubusercontent.com/29360565/66347782-66574c80-e955-11e9-959a-5248c6d17951.png)

**Comment by solvedDev** [comment]
Scheduled for the next update :)

![image](https://user-images.githubusercontent.com/33347616/66383037-8e2dcb00-e9bc-11e9-8c0e-7ab775fa5611.png)
