### ISSUE TITLE
[BUG] Saving items broken (description.identifier)

### ISSUE THREAD

**Issue by OGHorizon** [solvedDev/bridge.#90]
**Summary**
Json files not being able to save.

**To Reproduce**
1. Go to 'file'
2. Click on 'save'
3. Scroll down to 'you can't scroll down in the save process'
4. it's taking way too long to save 

**it's been 4 hours and the saving has not stopped**
A clear and concise description of what happened
**it should take five seconds
![bug]
*

**Screenshots / File Attachments**
(https://user-images.githubusercontent.com/46063050/66791557-95b40f00-eea9-11e9-888f-40db9ddc444e.JPG)

**Platform (please complete the following information):**
 - OS: [Windows 10]
 - App Version: [most recent version]

**Additional context**
I just wanna make addons man.

**Comment by solvedDev** [comment]
Fixed for the next version :)
