### ISSUE TITLE
[Bug] [Targeted version is Beta] Saving a file caused error message to pop up, and load infinitely preventing a save. 

### ISSUE THREAD

**Issue by bschurman1** [solvedDev/bridge.#95]
![bridge  10_18_2019 3_00_22 PM](https://user-images.githubusercontent.com/51575815/67125548-ac64a980-f1ba-11e9-85aa-28a45320cacb.png)
 
Replicable by choosing a honey_bottle template, and naming it honey_bottle. Change the stack size to 64 rather than 1, and save

**Comment by solvedDev** [comment]
Fixed on v0.13.14-dev
